##
#
# Makefile for XView Fonts Examples
#
# @(#)Makefile	1.9 91/07/08  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE	= disp_fonts.c 		\
		  disp_fonts2.c		\
		  fonts.c 		\
		  simple_font.c 	\
		  type_font.c		\
		  Imakefile		\
		  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.fonts}

include ${RULESET.include}
