##
#
# Makefile for XView Drag_&_Drop Examples
#
# @(#)Makefile	1.2 91/07/09  SMI
#
##

#
# Copyright (c) 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	dest.c \
		source1.c \
		arrow.bm \
		arrow_mask.bm \
		arrowb.bm \
		bullseye.bm \
		bullseyeI.bm \
		drop.icon \
		Imakefile \
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.dnd}

include ${RULESET.include}
