##
#
# Makefile for NeWS Wire Services
#
# @(#)Makefile	1.6 92/11/23
#
##

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../..

include ${SOURCEDIR}/config/Master.cfg

HEADERS			= helplib.h

MAKE.install.target	= install_h
HEADERS.public		= ${HEADERS}
INSTALL.headers.dir	= ${DEST.include.help}

include ${RULESET.include}


