##
#
# Makefile for XView Canvas Examples
#
# @(#)Makefile	1.8 91/02/13  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE		= canvas_event.c	\
			  canvas_input.c	\
			  line.c		\
			  scroll_view.c		\
			  split_views.c		\
			  Imakefile		\
			  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.canvas}

include ${RULESET.include}
