#
# @(#)Makefile	1.12 92/01/15
#

FILES	= Simple	\
	  SunCCgeneric	\
	  SunCCgeneric.fixed \
	  SunOS41	\
	  SunOSSVR4	\
	  SBrowser	\
	  SC1.0acc	\
	  SC1.0acc.fixed \
	  SC1.0acc.dist \
	  olit-dev	\
	  olit-dev-svr4

tool installtool deliverable all: ${FILES}

