##
#
# Makefile for XView SunView compatibility Examples
#
# @(#)Makefile	1.7 91/04/09  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE =	pw_draw.c		\
		gray_stencil.pr		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.sv_compat}

include ${RULESET.include}


