# "@(#)strings.awk	1.3  92/04/14 include/Xol SMI"    /* OLIT	*/

BEGIN {
	total = 0;
	c = "../../lib/libXol/OlStrings.c"
	h1 = "OlStrings.h"
	h2 = "OlStringsTable.h"

	print "#pragma	ident	\"@(#)strings.awk	1.3	92/04/14 lib/libXol SMI\"	" \
		"/* OLIT	*/" > c;
	# Insert StringList identifier
	print > c;
	print > c;

	print "#include <Xol/OlStringsTable.h>" > c;
	print > c;

	# Add the copyright file here.
	print "/*" > c;
	print " *	THIS FILE IS AUTOMATICALLY GENERATED." > c;
	print " *	DO NOT EDIT." > c;
	print " */" > c;
	print > c;
	print "const char	OlStrings[] = {" > c;

	print "#ifndef	_XOL_OLSTRINGS_H_" > h1;
	print "#define	_XOL_OLSTRINGS_H_" > h1;
	print > h1;

	print "#pragma	ident	\"@(#)strings.awk	1.3	92/04/14 include/Xol SMI\"	" \
		"/* olcommon:include/Xol/OlStrings.h 1.45.1.16	*/" > h1;
	# Insert StringList identifier
	print > h1;

	# Add the copyright file here.

	print "/*" > h1;
	print " *	THIS FILE IS AUTOMATICALLY GENERATED." > h1;
	print " *	DO NOT EDIT." > h1;
	print " */" > h1;
	print > h1;

	print "#ifndef	_XOL_OLSTRINGSTABLE_H_" > h2;
	print "#define	_XOL_OLSTRINGSTABLE_H_" > h2;
	print > h2;

	print "#pragma	ident	\"@(#)strings.awk	1.3	92/04/14 include/Xol SMI\"	" \
		"/* olcommon:include/Xol/OlStrings.h 1.45.1.16	*/" > h2;
	# Insert StringList identifier
	print > h2;

	# Add the copyright file here.

	print "/*" > h2;
	print " *	THIS FILE IS AUTOMATICALLY GENERATED." > h2;
	print " *	DO NOT EDIT." > h2;
	print " */" > h2;
	print > h2;
	print > h2;

	print "extern const char	OlStrings[];" > h2;
	print > h2;
}

/^;/ { next }

{
	printf("#define	%s \"%s\"\n", $1, \
		substr($1, 4, length($1) - 3)) > h1; 

	print "#define	" $1 "	((char*)&OlStrings[" total "])" > h2;

	for ( i = 4 ; i < length ($1) + 1; i++ )
		printf("'%s',", substr($1,i,1)) > c;
	printf("0,\n") > c;

	total += length ($1) - 2;
}

END {
	printf("0};\n") > c;

	print > h1;
	print "#endif	/* _XOL_OLSTRINGS_H_ */" > h1;

	print > h2;
	print "#endif	/* _XOL_OLSTRINGSTABLE_H_ */" > h2;
}
