##
#
# Makefile for XView Defaults Examples
#
# @(#)Makefile	1.7 91/02/13  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE		= default_size.c	\
			  default_text.c	\
			  Imakefile		\
			  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.defaults}

include ${RULESET.include}

