# Makefile for xnfont includes
#
# @(#)Makefile	1.1 92/07/15

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR               = ../..

include ${SOURCEDIR}/config/Master.cfg

HEADERS                 = fontnames.h

include ${RULESET.include}

