##
#
# Makefile for XView Menus Examples
#
# @(#)Makefile	1.9 91/04/12  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	menu.c			\
		menu_dir.c		\
		menu_dir2.c		\
		pin_menu.c		\
		simple_menu.c		\
		xv_menu.c		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.menus}

include ${RULESET.include}


