##
#
# Makefile for XView Cursor Examples
#
# @(#)Makefile	1.7 91/02/13  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE	= hot_spot.c 		\
		  simple_cursor.c 	\
		  stop_cursor.c		\
		  Imakefile		\
		  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.cursor}

include ${RULESET.include}


