##
#
# Makefile for olgx includes
#
# @(#)Makefile	1.2 91/01/14
#
##

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../..

include ${SOURCEDIR}/config/Master.cfg

HEADERS			= olgx.h

MAKE.install.target	= install_h
HEADERS.public		= ${HEADERS}
INSTALL.headers.dir	= ${DEST.include.olgx}

include ${RULESET.include}


