##
#
# Makefile for libXt application defaults files
#
# @(#)Makefile	1.10 93/09/29
##

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../..

include ${SOURCEDIR}/config/Master.cfg

MAKE.install.target	= install_file

INSTALL.file.dir	= ${DEST.app-defaults}

FILE			= 		\
			  Olbiff	\
			  Olmh		\
			#

include ${RULESET.include}
