SOURCEDIR               = ../../..

include ${SOURCEDIR}/config/Master.cfg

FONTS.bdf =	\
	a12biluc.bdf a12bluci.bdf a12butto.bdf a12iluci.bdf a12lucid.bdf \
	a12sbarh.bdf a12sbarv.bdf a12sldrh.bdf a12sldrv.bdf		 \
	b12bluci.bdf b12butto.bdf b12lucid.bdf b12sbarh.bdf b12sbarv.bdf \
	b12sldrh.bdf b12sldrv.bdf					 \
	c12bluci.bdf c12butto.bdf c12iluci.bdf c12lucid.bdf c12sbarh.bdf \
	c12sbarv.bdf c12sldrh.bdf c12sldrv.bdf				 \
	d12bluci.bdf d12butto.bdf d12iluci.bdf d12lucid.bdf d12sbarh.bdf \
	d12sbarv.bdf d12sldrh.bdf d12sldrv.bdf				 \
	e12bluci.bdf e12butto.bdf e12lucid.bdf e12sbarh.bdf e12sbarv.bdf \
	e12sldrh.bdf e12sldrv.bdf					 \
	f12bluci.bdf f12butto.bdf f12lucid.bdf f12sbarh.bdf f12sbarv.bdf \
	f12sldrh.bdf f12sldrv.bdf					 \
	g12bluci.bdf g12butto.bdf g12lucid.bdf g12sbarh.bdf g12sbarv.bdf \
	g12sldrh.bdf g12sldrv.bdf					 \
	h12bluci.bdf h12butto.bdf h12iluci.bdf h12lucid.bdf h12sbarh.bdf \
	h12sbarv.bdf h12sldrh.bdf h12sldrv.bdf

MAKE.install.target =	install.FONTS.bdf \
			.WAIT \
			install.FONTS.dir
INSTALL.fonts.dir = ${DEST.font.Xt+}

include ${RULESET.font}
