#
# @(#)Makefile	1.7 93/01/28 SMI
# Makefile for the Olit Progammer's Guide's Examples
#

#
#        Copyright (C) 1986,1991  Sun Microsystems, Inc
#                    All rights reserved.
#          Notice of copyright on this source code 
#          product does not indicate publication. 
# 
# RESTRICTED RIGHTS LEGEND: Use, duplication, or disclosure by 
# the U.S. Government is subject to restrictions as set forth 
# in subparagraph (c)(1)(ii) of the Rights in Technical Data
# and Computer Software Clause at DFARS 252.227-7013 (Oct. 1988) 
# and FAR 52.227-19 (c) (June 1987).
#
# This file is a product of Sun Microsystems, Inc. and is
# provided for unrestricted use provided that this legend is
# included on all media and as a part of the software
# program in whole or part.  Users may copy or modify this
# file without charge, but are not authorized to license or
# distribute it to anyone else except as part of a product or
# program developed by the user.
# 
# THIS FILE IS PROVIDED AS IS WITH NO WARRANTIES OF ANY KIND
# INCLUDING THE WARRANTIES OF DESIGN, MERCHANTIBILITY AND
# FITNESS FOR A PARTICULAR PURPOSE, OR ARISING FROM A COURSE
# OF DEALING, USAGE OR TRADE PRACTICE.
# 
# This file is provided with no support and without any
# obligation on the part of Sun Microsystems, Inc. to assist
# in its use, correction, modification or enhancement.
# 
# SUN MICROSYSTEMS, INC. SHALL HAVE NO LIABILITY WITH RESPECT
# TO THE INFRINGEMENT OF COPYRIGHTS, TRADE SECRETS OR ANY
# PATENTS BY THIS FILE OR ANY PART THEREOF.
# 
# In no event will Sun Microsystems, Inc. be liable for any
# lost revenue or profits or other special, indirect and
# consequential damages, even if Sun has been advised of the
# possibility of such damages.
# 
#    Sun Microsystems, Inc., 2550 Garcia Avenue,
#    Mountain View, California 94043.
#


SOURCEDIR		= ../../../..
INCLUDE.Rulesets.local  = ../Rulesets.local

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE	= fileview.c	\
		  fileview.h	\
		  fileview2.c	\
		  customer-svr4.mk

include ${INCLUDE.Rulesets.local}
