##
#
# Makefile for XView misc Examples
#
# @(#)Makefile	1.11 91/07/02  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	fullscreen.c 		\
		multi_display.c 	\
		multiscreen.c 		\
		screen.c 		\
		svrimage.c 		\
                vkbd_fonts.c            \
                vkbd_colors.c           \
		type_to_string.c	\
		textdemo.icon		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.misc}

include ${RULESET.include}


