#
#ident "@(#)Makefile	1.3 91/07/10"
#

SOURCEDIR       = ../..
 
include ${SOURCEDIR}/config/Master.cfg

SUBDIRS         = oldials \
                  olitbook
 
PUBLICSOURCE    = Makefile.customer
 
MAKE.install.target             = install_publicsource
INSTALL.publicsource.dir        = ${DEST.source.olit}
 
include ${RULESET.step}

