##
#
# Makefile for XView Frames Examples
#
# @(#)Makefile	1.10 91/02/28  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	command_frame.c 	\
	   	done_proc.c 		\
	   	frame_color.c 		\
	   	hdrs_n_footers.c 	\
	   	popup.c 		\
	   	simple_frame.c 		\
	   	subframe.c		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.frames}

include ${RULESET.include}


