.\" Copyright (c) 1994, Sun Microsystems, Inc.
.TH locale_env 1 "12 Nov 1992"
.IX "locale_env" "" "\f3locale_env\f1(1) \(em sets language" ""
.SH NAME
locale_env - program for openwin-sys
.SH SYNOPSIS
.LP
.B locale_env
.SH DESCRIPTION
.B locale_env
provides functionality for OpenWindows system initialization script openwin-sys
that is better done via a separate program.
.LP
.B locale_env
is used by openwin-sys and is not intended to be used directly.
.SH "SEE ALSO"
.BR openwin (1)
