##
#
# Makefile for XView extensions Examples
#
# @(#)Makefile	1.7 91/07/11  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE	= Bitmap.c \
		  bitmap.c \
		  Image.c \
		  image.c \
		  Logo.c \
		  logo.c \
		  bitmap.h \
		  bitmap_impl.h \
		  image.h \
		  image_impl.h \
		  logo.h \
		  logo_impl.h \
		  sample.bitmap \
		  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.extensions}

include ${RULESET.include}


