##
#
# Makefile for X11/NeWS help files
#
# @(#)Makefile 1.1 92/01/30
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#
##

SOURCEDIR	= ..

include ${SOURCEDIR}/config/Master.cfg

SUBDIRS		= handbooks

include ${RULESET.step}

