##
#
# Makefile for XView Textsw Examples
#
# @(#)Makefile	1.11 92/12/08  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	textsw.c 		\
		textsw.font.c 		\
		textswrc		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.textsw}

include ${RULESET.include}


