##
#
# Makefile for XView Scrollbar Examples
#
# @(#)Makefile	1.8 91/03/01  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE	= scroll_cells.c  	\
		  scroll_cells2.c 	\
		  scrollto.c      	\
		  Imakefile       	\
		  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.scrollbar}

include ${RULESET.include}


