##
#
# Makefile for XView selection_service Examples
#
# @(#)Makefile	1.8 91/03/01  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	long_seln.c 		\
		seln.c 			\
		seln_line.c 		\
		simple_seln.c 		\
		text_seln.c		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.seln_svc}

include ${RULESET.include}


