##
#
# Makefile for XView panel Examples
#
# @(#)Makefile	1.11 91/08/23  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	btn_menu.c		\
		choices.c		\
		client_data.c		\
		item_move.c		\
		list_glyphs.c		\
		list_6_glyphs.c		\
		panel_repaint.c		\
		quit.c			\
		repaint.c		\
		simple_panel.c		\
		slider.c		\
		stop_frame.c		\
		panel_dnd.c		\
		normal.icon		\
		normal2.icon		\
		busy.icon		\
		busy2.icon		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.panels}

include ${RULESET.include}


