##
#
# Makefile for Xol bitmaps
#
# @(#)Makefile	1.11 92/10/14
#
##

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../..

include ${SOURCEDIR}/config/Master.cfg

HEADERS			= ${HEADERS.private} \
			  ${HEADERS.public}

HEADERS.private		= \
			  clip_mask.xbm \
			  fcdoc.xbm \
			  fcfolder.xbm \
			  fcgoup.xbm \
                          mag_clip.xbm \
                          magnifier.xbm \
                          #

HEADERS.public		= \
			  biggestCurIn.h \
			  biggestCurOut.h \
			  busycurs.h \
			  busymask.h \
			  copymsk.h \
			  copysrc.h \
			  datadupe_drag.xbm \
			  datadupe_drag_mask.xbm \
			  datadupe_drop.xbm \
			  datadupe_drop_mask.xbm \
			  datadupe_insert.xbm \
			  datadupe_insert_mask.xbm \
			  datadupe_nodrop.xbm \
			  datadupe_nodrop_mask.xbm \
			  datamove_drag.xbm \
			  datamove_drag_mask.xbm \
			  datamove_drop.xbm \
			  datamove_drop_mask.xbm \
			  datamove_insert.xbm \
			  datamove_insert_mask.xbm \
			  datamove_nodrop.xbm \
			  datamove_nodrop_mask.xbm \
			  doc.xbm \
			  doc_mask.xbm \
			  docstack.xbm \
			  docstack_mask.xbm \
			  drop.xbm \
			  drop_mask.xbm \
			  dupcurs.h \
			  dupe_box.xbm \
			  dupe_box_mask.xbm \
			  dupedoc.xbm \
			  dupedoc_drag.xbm \
			  dupedoc_drag_mask.xbm \
			  dupedoc_drop.xbm \
			  dupedoc_drop_mask.xbm \
			  dupedoc_mask.xbm \
			  dupedoc_nodrop.xbm \
			  dupedoc_nodrop_mask.xbm \
			  dupestack.xbm \
			  dupestack_drag.xbm \
			  dupestack_drag_mask.xbm \
			  dupestack_drop.xbm \
			  dupestack_drop_mask.xbm \
			  dupestack_mask.xbm \
			  dupestack_nodrop.xbm \
			  dupestack_nodrop_mask.xbm \
			  dupmask.h \
			  folder.xbm \
			  folder_mask.xbm \
			  folderstack.xbm \
			  folderstack_mask.xbm \
			  hugeIn.h \
			  hugeOut.h \
			  insertdrop.xbm \
			  insertdrop_mask.xbm \
			  largeIn.h \
			  largeOut.h \
			  larrowOff.h \
			  larrowOn.h \
			  mediumIn.h \
			  mediumOut.h \
			  morearrow.h \
			  movcurs.h \
			  move_box.xbm \
			  move_box_mask.xbm \
			  movedoc.xbm \
			  movedoc_drag.xbm \
			  movedoc_drag_mask.xbm \
			  movedoc_drop.xbm \
			  movedoc_drop_mask.xbm \
			  movedoc_mask.xbm \
			  movedoc_nodrop.xbm \
			  movedoc_nodrop_mask.xbm \
			  movemsk.h \
			  movesrc.h \
			  movestack.xbm \
			  movestack_drag.xbm \
			  movestack_drag_mask.xbm \
			  movestack_drop.xbm \
			  movestack_drop_mask.xbm \
			  movestack_mask.xbm \
			  movestack_nodrop.xbm \
			  movestack_nodrop_mask.xbm \
			  movmask.h \
			  nodrop.xbm \
			  nodrop_mask.xbm \
			  pancurs.h \
			  panmask.h \
			  pt16CurIn.h \
			  pt16CurOut.h \
			  quescurs.h \
			  quesmask.h \
			  rarrowOff.h \
			  rarrowOn.h \
			  smallIn.h \
			  smallOut.h \
			  stdcurs.h \
			  stdmask.h \
			  targcurs.h \
			  targmask.h \
			  textdupe_drag.xbm \
			  textdupe_drag_mask.xbm \
			  textdupe_drop.xbm \
			  textdupe_drop_mask.xbm \
			  textdupe_insert.xbm \
			  textdupe_insert_mask.xbm \
			  textdupe_nodrop.xbm \
			  textdupe_nodrop_mask.xbm \
			  textmove_drag.xbm \
			  textmove_drag_mask.xbm \
			  textmove_drop.xbm \
			  textmove_drop_mask.xbm \
			  textmove_insert.xbm \
			  textmove_insert_mask.xbm \
			  textmove_nodrop.xbm \
			  textmove_nodrop_mask.xbm \
			  #


MAKE.install.target	= install_h
INSTALL.headers.dir	= ${DEST.include.Xol.bitmaps}

include ${RULESET.include}

