# Makefile for shared header files
#
# @(#)Makefile	1.39 94/02/08

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR	= ..

include ${SOURCEDIR}/config/Master.cfg

SUBDIRS		= 		\
		  Xol		\
		  Xolbitmaps	\
		  Xolgeometry 	\
		  bitmaps 	\
		  help		\
		  images 	\
		  olgx		\
		  xnfont	\
		  xview		\
		  xview_private

include ${RULESET.step}
