##
#
# Makefile for XView Notifier Examples
#
# @(#)Makefile	1.8 91/03/01  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE =	animate.c 		\
		interpose.c 		\
		notify.c 		\
		notify_input.c 		\
		ntfy_do_dis.c 		\
		ntfy_pipe.c 		\
		ntfy_sig.c		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.notifier}

include ${RULESET.include}


