#
# @(#)Makefile	1.57 93/11/02
#

FILES	= 	Makefile \
		gprof.db 	debug.db 	reorder.db \
		s494-galactic-debug.cfg \
		s494-galactic-reorder.cfg 	s494-galactic-gprof.cfg \
		s494-galactic.cfg	 	s494-galactic.db \
		s494-i386-galactic.cfg	 	\
		s494-i386-galactic-gprof.cfg	\
		svr4-xview.cfg		svr4-xview.db \
		xview.cfg		xview.db \
		kasso.cfg		kasso.db \
		gnu.cfg 		gnu.db \
		olit-dev-amber.cfg 	olit-dev-amber.db \
		home.cfg 

tool installtool deliverable all: ${FILES}


