##
#
# Makefile for XView Selection Examples
#
# @(#)Makefile	1.1 91/05/21  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	sel_hold.c		\
		sel_req.c		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.selection}

include ${RULESET.include}


