##
#
# Makefile for OpenWindows Man pages
#
# @(#)Makefile	1.6 93/10/18
#
##

#
# Copyright (c) 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../..

include ${SOURCEDIR}/config/Master.cfg

MANPAGE			= xview.7	


HEADERS.public		= ${HEADERS}
MAKE.install.target	= install_man
INSTALL.manpage.dir	= ${DEST.man7}

include ${RULESET.include}

