##
#
# Makefile for xview private headers
#
# The contents of this dir are symlinks pointing into the xview
# source tree under lib/libxview.  They are placed here when doing
# a make installtool within lib/libxview.
#
# @(#)Makefile	1.1 91/01/09
#
##

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR	= ../..

include ${SOURCEDIR}/config/Master.cfg

SUBDIRS		= 

include ${RULESET.step}

