##
#
# Makefile for XView Icons Examples
#
# @(#)Makefile	1.9 91/02/14  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE	= icon_demo.c 		\
		  icon_demo2.c		\
		  closed.icon 		\
		  closed2.icon 		\
		  open.icon		\
		  Imakefile		\
		  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.icons}

include ${RULESET.include}


