##
#
# Makefile for XView Color Examples
#
# @(#)Makefile	1.9 91/04/12  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE	= color.c 		\
		  animate.c 		\
		  color_animate.c 	\
		  color_logo.c 		\
		  color_objs.c 		\
		  color_panel.c 	\
		  x_draw.c 		\
		  example1.c 		\
		  example2.c 		\
		  example3.c 		\
		  example4.c		\
		  cardback.icon		\
		  Imakefile		\
		  Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.color}

include ${RULESET.include}


