##
#
# Makefile for XView ttysw Examples
#
# @(#)Makefile	1.8 91/10/14  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	sample_tty.c 		\
		textsw_to_ttysw.c 	\
		ttycurses.c 		\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.ttysw}

include ${RULESET.include}
