##
#
# Makefile for X11/NeWS Client Libraries
#
# @(#)Makefile 23.57 94/03/11
#
# Copyright (c) 1989 by Sun Microsystems, Inc.
#
##

SOURCEDIR	= ..

include ${SOURCEDIR}/config/Master.cfg

#
# 	IMPORTANT: compat must be before any lib* directories
#		that have corresponding compat/lib* directories
#

SUBDIRS		=		\
		  app-defaults	\
		  libmisc	\
		  libolgx	\
		  libXol	\
		  ${I18N_LIBS}	\
		  spot_help	\
		  libxview	\
		  wckindl10n

NOTBUILT	=

include ${RULESET.step}

