##
#
# Makefile for XView notice Examples
#
# @(#)Makefile	1.7 91/04/09  SMI
#
##

#
# Copyright (c) 1990, 1991 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../../..

include ${SOURCEDIR}/config/Master.cfg

PUBLICSOURCE  =	notice.c		\
		simple_notice.c		\
		trigger_notice.c	\
		Imakefile		\
		Makefile.customer

MAKE.install.target		= install_publicsource
INSTALL.publicsource.dir	= ${DEST.source.xview.examples.notice}

include ${RULESET.include}


