#ident @(#)Makefile	23.18 94/04/06

#
# Makefile for OpenWindows Man pages
#

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../..

include ${SOURCEDIR}/config/Master.cfg


MANPAGE			= fish_props.6	\
			  olbiff.6	\
			  olmh.6	\
			  olitsampler.6 \
			  olittable.6	\
			  realxfishdb.6 \
			  spider.6

MAKE.install.target	= install_man
INSTALL.manpage.dir	= ${DEST.man6}

include ${RULESET.include}


