.\" Copyright (c) 1994 - Sun Microsystems, Inc.
.TH olitsampler 6 "19 July 91"
.IX "olitsampler" "" "\f3olitsampler\f1(6) \(em OLIT widget demo" ""
.IX "demo" "OLIT" "demo" "OLIT demo program \(em \f3olitsampler\f1(6)"
.SH NAME
olitsampler \- OLIT widget demo program
.SH SYNOPSIS
.B olitsampler
.SH DESCRIPTION
.B Olitsampler
is a simple application program that demonstrates
OLIT widgets.
.SH SEE ALSO
.I "OLIT Reference Manual"
