##
#
# Makefile for X11 bitmaps
#
# @(#)Makefile	23.10 91/05/07
#
##

#
# Copyright (c) 1990 by Sun Microsystems, Inc.
#

SOURCEDIR		= ../..

include ${SOURCEDIR}/config/Master.cfg

HEADERS			= 1x1 		\
			  2x2 		\
			  black 	\
			  black6	\
			  box6		\
			  boxes 	\
			  calculator 	\
			  cntr_ptr 	\
			  cntr_ptrmsk 	\
			  cross_weave 	\
			  dimple1 	\
			  dimple3 	\
			  dot 		\
			  dropbar7 	\
			  dropbar8 	\
			  escherknot	\
			  flagdown 	\
			  flagup 	\
			  flipped_gray 	\
			  gray 		\
			  gray1		\
			  gray3		\
			  hlines2	\
			  hlines3	\
			  icon 		\
			  keyboard16	\
			  left_ptr 	\
			  left_ptrmsk 	\
			  letters	\
			  light_gray 	\
			  mailempty 	\
			  mailemptymsk 	\
			  mailfull 	\
			  mailfullmsk 	\
			  mensetmanus	\
			  menu10	\
			  menu12	\
			  menu16	\
			  menu8		\
			  noletters 	\
			  opendot 	\
			  opendotMask 	\
			  plaid		\
			  right_ptr 	\
			  right_ptrmsk 	\
			  root_weave 	\
			  scales 	\
			  sipb 		\
			  star 		\
			  starMask 	\
			  stipple 	\
			  target 	\
			  terminal	\
			  txtmv		\
			  txtmvmask	\
			  txtmvmore	\
			  txtdup	\
			  txtdupmask	\
			  txtdupmore	\
			  txtmvok	\
			  txtmvokmask	\
			  txtmvokmore	\
			  txtdupok	\
			  txtdupokmask	\
			  txtdupokmore	\
			  tie_fighter 	\
			  vlines2	\
			  vlines3	\
			  weird_size	\
			  wide_weave 	\
			  wierd_size 	\
			  wingdogs 	\
			  woman 	\
			  xfd_icon 	\
			  xlogo11 	\
			  xlogo16 	\
			  xlogo32 	\
			  xlogo64 

MAKE.install.target	= install_h
HEADERS.public		= ${HEADERS}
INSTALL.headers.dir	= ${DEST.include.X11.bitmaps}

include ${RULESET.include}

